//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnTangle.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnTangle.Languages.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви впевнені, що хочете відмінити налаштування?.
        /// </summary>
        internal static string CancelMessage {
            get {
                return ResourceManager.GetString("CancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вдалося зберегти налаштування. Повторіть спробу.\n\nПомилка:.
        /// </summary>
        internal static string FailedApply {
            get {
                return ResourceManager.GetString("FailedApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибрана функція &quot;Зміна регістра&quot;.
        /// </summary>
        internal static string FuncCaseChanging {
            get {
                return ResourceManager.GetString("FuncCaseChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибрана функція &quot;Обернення&quot;.
        /// </summary>
        internal static string FuncReverser {
            get {
                return ResourceManager.GetString("FuncReverser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибрана функція &quot;Транслітерація&quot;.
        /// </summary>
        internal static string FuncTranslit {
            get {
                return ResourceManager.GetString("FuncTranslit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування збережено!.
        /// </summary>
        internal static string SuccessfullApply {
            get {
                return ResourceManager.GetString("SuccessfullApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Програма прихована в панелі прихованих значків. Щоб відкрити вікно натисніть лівою кнопкою миші по значку..
        /// </summary>
        internal static string TipTextHide {
            get {
                return ResourceManager.GetString("TipTextHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версія: .
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
